package co.edu.usbcali.modelo;
// Generated 16/03/2015 02:47:53 PM by Hibernate Tools 4.0.0



/**
 * Anexos generated by hbm2java
 */
public class Anexos  implements java.io.Serializable {


     private Long codigoAnexo;
     private Articulos articulos;
     private String nombre;
     private String url;
     private String archivo;
     private String formato;

    public Anexos() {
    }

	
    public Anexos(Long codigoAnexo, Articulos articulos, String nombre, String formato) {
        this.codigoAnexo = codigoAnexo;
        this.articulos = articulos;
        this.nombre = nombre;
        this.formato = formato;
    }
    public Anexos(Long codigoAnexo, Articulos articulos, String nombre, String url, String archivo, String formato) {
       this.codigoAnexo = codigoAnexo;
       this.articulos = articulos;
       this.nombre = nombre;
       this.url = url;
       this.archivo = archivo;
       this.formato = formato;
    }
   
    public Long getCodigoAnexo() {
        return this.codigoAnexo;
    }
    
    public void setCodigoAnexo(Long codigoAnexo) {
        this.codigoAnexo = codigoAnexo;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }




}


